
services:
# ----------------- Service Containers -----------------
  frontend:
    image: frontend:latest
    build:
      context: ./frontend-service-go
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - VaporNet

  # PRO290VaporGameAPI:
  #   build: ./PRO290VaporGameAPI
  #   image: vaporgameapi
  #   ports:
  #     - 8080:8080
  #   networks:
  #     - VaporNet

  games-service:
    build: ./games-service-go
    container_name: games-service
    ports:
      - "8080"
    environment:
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_REGION=us-west-2
      - DYNAMODB_ENDPOINT=http://VaporGameDynamoDB:8000
      - CONSUL_ADDRESS=consul:8500
    depends_on:
      - VaporGameDynamoDB
    networks:
      - VaporNet
    # deploy:
    #   mode: replicated
    #   replicas: 3

    
  carts-service:
    build: ./carts-service-go
    container_name: carts-service
    ports:
      - "8080"
    environment:
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_REGION=us-west-2
      - DYNAMODB_ENDPOINT=http://VaporCartDynamoDB:8000
    depends_on:
      - VaporCartDynamoDB
      - consul
      - traefik
    networks:
      - VaporNet     
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.games.rule=PathPrefix(`/games`)"
      - "traefik.http.services.games.loadbalancer.server.port=8080"
    # depends_on:
    #   - VaporDBdynamo
    # deploy:
    #   mode: replicated
    #   replicas: 3




# ----------------- Database Containers -----------------
  VaporGameDynamoDB:
    image: amazon/dynamodb-local:latest
    container_name: VaporGameDynamoDB
    ports:
      - "8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data/game"
    volumes:
      - "./dynamodb_data:/home/dynamodblocal/data/game"
    networks:
      - VaporNet
  
  VaporCartDynamoDB:
    image: amazon/dynamodb-local:latest
    container_name: VaporCartDynamoDB
    ports:
      - "8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data/cart"
    volumes:
      - "./dynamodb_data:/home/dynamodblocal/data/cart"
    networks:
      - VaporNet

  # ----- Init DynamoDB Tables -----
  VaporCartDynamoDB-init:
    depends_on:
      - VaporCartDynamoDB
    image: amazon/aws-cli
    environment:
      AWS_ACCESS_KEY_ID: admin
      AWS_SECRET_ACCESS_KEY: admin
    command: >-
      dynamodb create-table
          --table-name Carts
          --attribute-definitions
              AttributeName=id,AttributeType=S
          --key-schema
              AttributeName=id,KeyType=HASH
          --billing-mode PAY_PER_REQUEST
          --endpoint-url http://VaporCartDynamoDB:8000 --region us-west-2
    networks:
      - VaporNet

# ----------------- Registry and Gateway -----------------
  consul:
    image: consul:1.12.2
    ports:
      - "8500:8500"
    networks:
      - VaporNet
  traefik:
    image: traefik:v2.4
    command:
      - --entrypoints.web.address=:80
      - --api.insecure=true
    ports:
      - "80:80"
      - "8080:8080"
    depends_on:
      - consul
    networks:
      - VaporNet
  # SEN300EurekaLightRegistry:
  #   container_name: SEN300EurekaLightRegistry
  #   image: steeltoeoss/eureka-server:latest
  #   # restart: always
  #   hostname: SEN300EurekaLightRegistry
  #   ports:
  #     - "8762:8761"
  #   networks:
  #     - VaporNet

  # SEN300LightAPIOcelotGateway:
  #   container_name: SEN300LightAPIOcelotGateway
  #   build:
  #     context: ./dotnet-apigateway-ocelot
  #     dockerfile: Dockerfile
  #   image: sen300ocelotgatewayapi:1
  #   # restart: always
  #   hostname: SEN300LightAPIOcelotGateway
  #   ports:
  #     - "5042:8080"
  #   networks:
  #     - VaporNet
  #   depends_on:
  #     - SEN300EurekaLightRegistry

# ----------------- Kafka and Zookeeper -----------------
  Zookeeper:  
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2182:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - VaporNet

  Kafka: 
    image: 'bitnami/kafka:latest'
    restart: always
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=Zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://Kafka:9092
    depends_on:
      - Zookeeper
    networks:
      - VaporNet
# ------------------------- EMAIl ------------------------

  # Emailer:  #Kafka Message consumer
  #   build: ./email_service
  #   restart: always
  #   image: email_service
  #   ports:
  #     - 0000:8080
  #   depends_on:
  #     - Kafka
  #   networks:
  #     - VaporNet

networks:
  VaporNet:
    external: false
  
volumes:
  dynamodb_data:
