
services:
# ----------------- Service Containers -----------------
  frontend-service:
    image: frontend:latest
    build:
      context: ./frontend-service-go
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - VaporNet
    depends_on:
      - traefik
    restart:
      always
    environment:
      - CONSUL_ADDRESS=consul:8500
      - SERVICE_NAME=frontend-service
      - SERVICE_ID=frontend-service-1
      - SERVICE_PORT=3000
      - TRAEFIK_ENABLE=true
      - TRAEFIK_HTTP_ROUTERS_FRONTEND_RULE=PathPrefix(`/`)
      - TRAEFIK_HTTP_SERVICES_FRONTEND_LOADBALANCER_SERVER_PORT=3000


  games-service:
    build: ./games-service-go
    # container_name: games-service
    ports:
      - "3000"
    environment:
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_REGION=us-west-2
      - DYNAMODB_ENDPOINT=http://VaporGameDynamoDB:8000
      - CONSUL_ADDRESS=consul:8500
      - SERVICE_NAME=games-service
      - SERVICE_ID=games-service-1
      - SERVICE_PORT=3000
      - TRAEFIK_ENABLE=true
      - TRAEFIK_HTTP_ROUTERS_GAMES_RULE=PathPrefix(`/games`)
      - TRAEFIK_HTTP_SERVICES_GAMES_LOADBALANCER_SERVER_PORT=3000
    depends_on:
      - VaporGameDynamoDB
    networks:
      - VaporNet     
    deploy:
      mode: replicated
      replicas: 3

    
  carts-service:
    build: ./carts-service-go
    # container_name: carts-service
    ports:
      - "3000"
    environment:
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_REGION=us-west-2
      - DYNAMODB_ENDPOINT=http://VaporCartDynamoDB:8000
      - CONSUL_ADDRESS=consul:8500
      - SERVICE_NAME=carts-service
      - SERVICE_ID=carts-service-1
      - SERVICE_PORT=3000
      - TRAEFIK_ENABLE=true
      - TRAEFIK_HTTP_ROUTERS_CARTS_RULE=PathPrefix(`/carts`)
      - TRAEFIK_HTTP_SERVICES_CARTS_LOADBALANCER_SERVER_PORT=3000
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - VaporCartDynamoDB
      - consul
      - traefik
    networks:
      - VaporNet     
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.carts.rule=PathPrefix(`/carts`)"
      - "traefik.http.services.carts.loadbalancer.server.port=3000"
    deploy:
      mode: replicated
      replicas: 3

  auth-service:
    build: ./auth-service
    # container_name: auth-service
    ports:
      - "3000"
    environment:
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_REGION=us-west-2
      - DYNAMODB_ENDPOINT=http://VaporAuthDynamoDB:8000
      - CONSUL_ADDRESS=consul:8500
      - SERVICE_NAME=auth-service
      - KAFKA_BROKER=kafka:9092
      - SERVICE_ID=auth-service-1
      - SERVICE_PORT=3000
      - TRAEFIK_ENABLE=true
      - TRAEFIK_HTTP_ROUTERS_FRONTEND_RULE=PathPrefix(`/auth`)
      - TRAEFIK_HTTP_SERVICES_FRONTEND_LOADBALANCER_SERVER_PORT=3000
    depends_on:
      - VaporAuthDynamoDB
      - consul
      - traefik
    networks:
      - VaporNet     
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.rule=PathPrefix(`/auth`)"
      - "traefik.http.services.auth.loadbalancer.server.port=3000"
    deploy:
      mode: replicated
      replicas: 3





# ----------------- Database Containers -----------------
  VaporGameDynamoDB:
    image: amazon/dynamodb-local:latest
    container_name: VaporGameDynamoDB
    ports:
      - "8888:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    volumes:
      - "./dynamodb_data/game:/home/dynamodblocal/data"
    networks:
      - VaporNet
  
  VaporCartDynamoDB:
    image: amazon/dynamodb-local:latest
    container_name: VaporCartDynamoDB

    ports:
      - "8889:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    volumes:
      - "./dynamodb_data/cart:/home/dynamodblocal/data"
    networks:
      - VaporNet
  
  VaporAuthDynamoDB:
    image: amazon/dynamodb-local:latest
    ports:
      - "8000"
    volumes:
      - "./dynamodb_data/auth:/home/dynamodblocal/data"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data"
    networks:
      - VaporNet

  
# ----------------- Registry and Gateway -----------------
  consul:
    image: consul:1.12.2
    ports:
      - "8500:8500"
    networks:
      - VaporNet
    restart: on-failure
  traefik:
    image: traefik:latest
    container_name: traefik
    command:
        - '--api.insecure=true'
        - '--providers.consulcatalog=true'
        - '--providers.consulcatalog.prefix=traefik'
        - '--providers.consulcatalog.endpoint.address=consul:8500'
        - '--serversTransport.insecureSkipVerify=true'
        - '--entryPoints.web.address=:80'
        - '--log.level=DEBUG'
    ports:
      - 80:80
      - 8080:8080
    restart: always
    networks:
      - VaporNet
  # SEN300EurekaLightRegistry:
  #   container_name: SEN300EurekaLightRegistry
  #   image: steeltoeoss/eureka-server:latest
  #   # restart: always
  #   hostname: SEN300EurekaLightRegistry
  #   ports:
  #     - "8762:8761"
  #   networks:
  #     - VaporNet

  # SEN300LightAPIOcelotGateway:
  #   container_name: SEN300LightAPIOcelotGateway
  #   build:
  #     context: ./dotnet-apigateway-ocelot
  #     dockerfile: Dockerfile
  #   image: sen300ocelotgatewayapi:1
  #   # restart: always
  #   hostname: SEN300LightAPIOcelotGateway
  #   ports:
  #     - "5042:8080"
  #   networks:
  #     - VaporNet
  #   depends_on:
  #     - SEN300EurekaLightRegistry

# ----------------- Kafka and Zookeeper -----------------
  Zookeeper:  
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2182:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - VaporNet

  Kafka: 
    image: 'bitnami/kafka:latest'
    restart: always
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=Zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://Kafka:9092
    depends_on:
      - Zookeeper
    networks:
      - VaporNet
# ------------------------- EMAIl ------------------------

  # Emailer:  #Kafka Message consumer
  #   build: ./email_service
  #   restart: always
  #   image: email_service
  #   ports:
  #     - 0000:8080
  #   depends_on:
  #     - Kafka
  #   networks:
  #     - VaporNet

networks:
  VaporNet:
    external: false
  
volumes:
  dynamodb_data:
